### ISSUE TITLE
Simulator Data Gathering

### ISSUE THREAD

**Issue by daymare** [PalouseRobosub/robosub_simulator#90]
## Introduction
Write a script for the simulator that moves the sub to random positions and orientations in the pool.

## Background
We need to generate negative image data for object detection learning algorithms on the sub. Negative images are images that do not contain the object we are looking for. Negative images need to be extensive and comprehensive, everything that is not what we are looking for needs to be included.

## Task
The script needs to do these things while it is running:
 - [ ] Move the sub to a random position and orientation every 3-5 seconds
 - [ ] In between each move rotate the sub randomly about each axis

## Constraints
 - The sub needs to be moved somewhere in the pool (no moving to the void, inside of the walls, or above the water)
 - Most of the time the sub should be moved somewhere in the competition field
 - Sometimes the sub should be moved to the far sides of the pool. I.E. we should get some data that is not in the obstacle course  

## Extra Credit
 - [ ] Remove positive object from the pool automatically
 - [ ] Automatically start and stop bagging images using [rosbag](http://robosub-vm.eecs.wsu.edu/wiki/cs/ros/rosbag/start)
 - [ ] Specify object to collect negative data for
 - [ ] Add an option to remove all game objects

## Extra Extra Credit
 - [ ] Automatically collect positive data (ask @daymare for details)

## Questions
Ask @daymare for questions or more details.

**Comment by skallaher** [comment]
Needs updates to reflect developments since submitted.
